# Generated by Django 3.2.7 on 2021-09-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='user',
            new_name='user_email',
        ),
    ]
