# Generated by Django 3.2.7 on 2021-09-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_rename_user_posting_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='user_email',
            new_name='user',
        ),
    ]
