# Generated by Django 3.2.7 on 2021-10-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211004_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
