# Generated by Django 3.2.7 on 2021-09-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=20)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('date_birth', models.DateField(null=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
