# Generated by Django 3.2.7 on 2021-09-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('phone', models.IntegerField()),
                ('web_site', models.CharField(max_length=100, null=True)),
                ('information', models.TextField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
