# Generated by Django 3.2.7 on 2021-09-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
