# Generated by Django 3.2.7 on 2021-09-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_pw', models.CharField(max_length=100)),
                ('user_tel', models.IntegerField()),
                ('user_info', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
