# Generated by Django 3.2.7 on 2021-09-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_pw',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_tel',
        ),
        migrations.AddField(
            model_name='user',
            name='other_information',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
