
{'USER': 'pro',
 '__CFBundleIdentifier': 'com.microsoft.VSCode',
 'COMMAND_MODE': 'unix2003',
  'LOGNAME': 'pro',
  'PATH': '/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pro/opt/miniconda3/envs/westagram/bin:/Users/pro/opt/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.9/bin',
  'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.bQKgJURvyb/Listeners',
  'SHELL': '/bin/zsh',
  'HOME': '/Users/pro',
  '__CF_USER_TEXT_ENCODING': '0x1F5:0x3:0x33',
  'TMPDIR': '/var/folders/t5/rq1_ylz94vzc8s2hnxtp0yh80000gn/T/',
  'XPC_SERVICE_NAME': '0',
  'XPC_FLAGS': '0x0',
  'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined',
  'SHLVL': '1',
  'PWD': '/Users/pro/Desktop/Codings/westagram/25-westagram-backend/students/minchan/westagram',
  'OLDPWD': '/Users/pro/Desktop/Codings/westagram/25-westagram-backend',
  'CONDA_EXE': '/Users/pro/opt/miniconda3/bin/conda',
  'CONDA_PYTHON_EXE': '/Users/pro/opt/miniconda3/bin/python',
  'CONDA_SHLVL': '2',
  'CONDA_PREFIX': '/Users/pro/opt/miniconda3/envs/westagram',
  'CONDA_DEFAULT_ENV': 'westagram',
  'CONDA_PROMPT_MODIFIER': '(westagram) ',
  'TERM_PROGRAM': 'vscode',
  'TERM_PROGRAM_VERSION': '1.60.1',
  'LANG': 'ko_KR.UTF-8',
  'COLORTERM': 'truecolor',
  'VSCODE_GIT_IPC_HANDLE': '/var/folders/t5/rq1_ylz94vzc8s2hnxtp0yh80000gn/T/vscode-git-cdbf25ec9f.sock',
  'GIT_ASKPASS': '/Users/pro/Desktop/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh',
  'VSCODE_GIT_ASKPASS_NODE': '/Users/pro/Desktop/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)',
  'VSCODE_GIT_ASKPASS_MAIN': '/Users/pro/Desktop/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js',
  'TERM': 'xterm-256color',
  '_CE_M': '',
  '_CE_CONDA': '',
  'CONDA_PREFIX_1': '/Users/pro/opt/miniconda3',
  '_': '/Users/pro/opt/miniconda3/envs/westagram/bin/python3.8',
  'DJANGO_SETTINGS_MODULE': 'westagram.settings',
  'TZ': 'Asia/Seoul',
  'RUN_MAIN': 'true',
  'SERVER_NAME': '1.0.0.127.in-addr.arpa',
  'GATEWAY_INTERFACE': 'CGI/1.1',
  'SERVER_PORT': '8000',
  'REMOTE_HOST': '',
  'CONTENT_LENGTH': '',
  'SCRIPT_NAME': '',
  'SERVER_PROTOCOL': 'HTTP/1.1',
  'SERVER_SOFTWARE': 'WSGIServer/0.2',
  'REQUEST_METHOD': 'GET',
  'PATH_INFO': '/minchan/user_login',
  'QUERY_STRING': '',
  'REMOTE_ADDR': '127.0.0.1',
  'CONTENT_TYPE': 'text/plain',
  'HTTP_HOST': '127.0.0.1:8000',
  'HTTP_USER_AGENT': 'HTTPie/2.5.0',
  'HTTP_ACCEPT_ENCODING': 'gzip,deflate',
  'HTTP_ACCEPT': '*/*',
  'HTTP_CONNECTION': 'keep-alive',
  'wsgi.input': "< django.core.handlers.wsgi.LimitedStream object at 0x7f84d02ec460 >" ,
  'wsgi.errors': "< _io.TextIOWrapper name = '<stderr>' mode = 'w' encoding = 'utf-8' >" ,
  'wsgi.version': (1,0),
  'wsgi.run_once': False,
  'wsgi.url_scheme': 'http',
  'wsgi.multithread': True,
  'wsgi.multiprocess': False,
  'wsgi.file_wrapper': "< class 'wsgiref.util.FileWrapper' >"
   }

test = False or False
print(test)