# Generated by Django 3.2.7 on 2021-09-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
