# Generated by Django 3.2.7 on 2021-09-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='etc_info',
            field=models.CharField(default='username을 정해주세요', max_length=500, null=True),
        ),
    ]
